natura-cosmeticos/natds-commons

.typo-ci.yml

chore: update Typo CI config file

---

packages/natds-themes/properties/globals/opacity/opacity.json

feat(opacity): add missing `veryHigh` opacity

---

package.json
packages/natds-themes/config/android/buildResourcesOutput.js
packages/natds-themes/config/android/buildResourcesOutput.test.js

test(natds-themes): add missing test

---

.travis.yml
lerna.json

DSY-1515
This PR revert some changes that broke the natds-themes pipeline.
Also, adds files to be ignored by lerna when defining if a package should be released.

chore: revert travis changes, add files to lerna ignoreChanges

---

packages/natds-icons/CONTRIBUTING.md

Adding info about how to add new icons

 docs: update docs

---

.typo-ci.yml
packages/natds-icons/README.md

DSY-1667
This PR brings the following changes:
* Update README file about how to use `natds-icons` in different platforms we give support
- N/A

docs: update natds-icons readme

---

scripts/create-icons-vars.sh

- Fix `create_icons_vars` script

fix: [DSY-1750] update create icons vars

---

packages/natds-icons/README.md
packages/natds-icons/ios/NatDSIcons/NatDSIcons.podspec

- Updates ios icons documentation
- Updates podspec's documentation url

Docs: Update ios icons documentation

---

lerna.json
packages/natds-lint/CHANGELOG.md
packages/natds-lint/README.md
packages/natds-lint/base/index.js
packages/natds-lint/base/rules/best-practices.js
packages/natds-lint/base/rules/errors.js
packages/natds-lint/base/rules/es6.js
packages/natds-lint/base/rules/imports.js
packages/natds-lint/base/rules/node.js
packages/natds-lint/base/rules/strict.js
packages/natds-lint/base/rules/style.js
packages/natds-lint/base/rules/variables.js
packages/natds-lint/index.js
packages/natds-lint/jest/index.js
packages/natds-lint/package.json
packages/natds-lint/react/index.js
packages/natds-lint/react/rules/react-hooks.js
packages/natds-lint/react/rules/react.js
packages/natds-lint/typescript/index.js
packages/natds-storybook-themes/package.json
packages/natds-themes/package.json
packages/natds-token-search/package.json
renovate.json
yarn.lock

This PR add a package to share a commons lint configuration across all design system JS/TS packages

Add lint package

---

lerna.json
packages/natds-icons/android/build.gradle

Update kotlin version to 1.4.20 at Android package.

[FIX] Update kotlin version at Android package

---

packages/natds-cli/package.json

affects: @naturacosmeticos/natds-cli
DSY-2481

chore(natds-cli): update package name

---

packages/natds-token-search/package.json
yarn.lock

update natds-themes dependency on natds-token-search

fix(natds-token-search): update natds-themes dependency

---

packages/natds-themes/package.json
yarn.lock

DSY-000
Downgrade svg2vectordrawable to fix android environment, this library contains a dependency that has been discontinued (svgo), however we will need another library that meets this demand.

deps(svg2): downgrade svg2vectordrawable

---

packages/natds-lint/base/rules/style.js
packages/natds-lint/react/rules/react-hooks.js
packages/natds-lint/react/rules/react.js

affects: @naturacosmeticos/eslint-config-natds
DSY-2547
This PR updates the lint rules that were being overridden in the natds-js and natds-rn library settings

fix(natds-lint): updates lint rules

---

packages/natds-lint/base/rules/imports.js

affects: @naturacosmeticos/eslint-config-natds
DSY-2574

chore(natds-lint): update rules

---

packages/natds-themes/properties/brands/natura/light.json

DSY-000 - 
here we are testing the entire update flow

fix(natds-themes): tokens update-testing the entire update flow

---

packages/natds-themes/package.json

doc: fix documentation build

---

packages/natds-themes/package.json

doc(natds-themes): fix documentation build

---

packages/natds-themes/bin/colors-to-code-output.json

fix(natds-themes): tokens update

---

packages/natds-themes/package.json
packages/natds-themes/properties/brands/aesop/dark.json
packages/natds-themes/properties/brands/aesop/light.json
packages/natds-themes/properties/brands/aesop/typography.json
packages/natds-themes/properties/brands/avon/dark.json
packages/natds-themes/properties/brands/avon/light.json
packages/natds-themes/properties/brands/theBodyShop/dark.json
packages/natds-themes/properties/brands/theBodyShop/light.json
packages/natds-themes/properties/brands/theBodyShop/spectrum.json
packages/natds-token-search/src/Form.js
packages/natds-token-search/src/store/tokens.js

Color tokens have been harmonized
Added theme in search-token

Dsy 3041 harmonization and add theme in search-token

---

packages/natds-themes/properties/brands/natura/typography.json
packages/natds-themes/properties/brands/natura_v2/typography.json

DSY-3165
Change fontFamily natura and natura_v2

fix(natds-themes): change fontFamily natura n_v2

---

packages/natds-themes/package.json
packages/natds-themes/properties/brands/natura/typography.json
packages/natds-themes/properties/brands/natura_v2/typography.json

Change typografy Natura and Natura_v2

Dsy 3165 v2

---

packages/natds-themes/config/react-native/static/index.js
packages/natds-themes/config/shared/constants.js
packages/natds-themes/config/web/static/index.js
packages/natds-themes/package.json
packages/natds-themes/properties/brands/avon_v2/asset-dark.json
packages/natds-themes/properties/brands/avon_v2/asset-light.json
packages/natds-themes/properties/brands/avon_v2/components/button.json
packages/natds-themes/properties/brands/avon_v2/components/shortcut.json
packages/natds-themes/properties/brands/avon_v2/dark.json
packages/natds-themes/properties/brands/avon_v2/light.json
packages/natds-themes/properties/brands/avon_v2/spectrum.js
packages/natds-themes/properties/brands/avon_v2/spectrum.json
packages/natds-themes/properties/brands/avon_v2/spectrum.test.js
packages/natds-themes/properties/brands/avon_v2/typography.json
packages/natds-token-search/src/Form.js
packages/natds-token-search/src/store/tokens.js

Dsy 3268 - create theme avon_v2

---

packages/natds-themes/properties/globals/components/typography.json
packages/natds-themes/properties/platforms/web/typography.json

feat(natds-themes): update typography

---

packages/natds-themes/config/shared/actions/registerCreateTypefaceAction.test.js
packages/natds-token-search/src/styles/global.js

commons - remove ref font helvetica in file test

Dsy 3452 - commons -remove ref font helvetica in file test

---

packages/natds-themes/properties/brands/avon_v2/spectrum.js

Update spectrum.js - test

---

package.json

Update package.json - octokit breaking pipeline

---

packages/natds-themes/config/shared/actions/registerTypeDefinitionsAction.js

PT and ES interface generator for Beauty Consultancy logo

Dsy 3563 - PT and ES interface generator for Beauty Consultancy logo

---

packages/natds-themes/config/shared/transforms/registerOptimizeSvgTransform.js

DSY-3565
apply function to optimize svg PT ES

refactor(natds-themes):  apply function to optimize svg PT ES

---

packages/natds-lint/package.json

updaling natds-lint versions

---

packages/natds-themes/config/shared/helpers/helpers.js

fix(natds-themes):  verify-version

---

packages/natds-cli/package.json
packages/natds-icons/package.json
packages/natds-lint/package.json
packages/natds-storybook-themes/package.json

bumping versions to release icons 

---

packages/natds-themes/properties/brands/aesop/dark.json
packages/natds-themes/properties/brands/aesop/light.json
packages/natds-themes/properties/brands/avon/dark.json
packages/natds-themes/properties/brands/avon/light.json
packages/natds-themes/properties/brands/avon_v2/dark.json
packages/natds-themes/properties/brands/avon_v2/light.json
packages/natds-themes/properties/brands/biome/dark.json
packages/natds-themes/properties/brands/biome/light.json
packages/natds-themes/properties/brands/casaEestilo/dark.json
packages/natds-themes/properties/brands/casaEestilo/light.json
packages/natds-themes/properties/brands/consultoriaDeBeleza/dark.json
packages/natds-themes/properties/brands/consultoriaDeBeleza/light.json
packages/natds-themes/properties/brands/natura/dark.json
packages/natds-themes/properties/brands/natura/light.json
packages/natds-themes/properties/brands/natura_v2/dark.json
packages/natds-themes/properties/brands/natura_v2/light.json
packages/natds-themes/properties/brands/theBodyShop/dark.json
packages/natds-themes/properties/brands/theBodyShop/light.json

Dsy 3803 Color Token Updates

---

packages/natds-themes/package.json

DSY-3951
bump version 0.59.23 to 0.60.0

bump version 0.59.23 to 0.60.0

---

packages/natds-cli/package.json
packages/natds-lint/package.json
packages/natds-themes/package.json

DSY-3951
bump version natds-cli natds-lint natds-themes

feat(natds-themes):  bump version natds-cli natds-lint natds-themes

---

packages/natds-cli/package.json
packages/natds-lint/package.json
packages/natds-storybook-themes/package.json
packages/natds-themes/package.json

DSY-3951
bump version cli lint themes storybook

bump version cli lint themes storybook

---

packages/natds-cli/package.json
packages/natds-lint/package.json
packages/natds-storybook-themes/package.json
packages/natds-themes/package.json

bump version cli lint storybook themes v2

---

packages/natds-cli/package.json
packages/natds-lint/package.json
packages/natds-storybook-themes/package.json
packages/natds-themes/package.json

bump version cli lint storybook theme v3

---

packages/natds-cli/package.json
packages/natds-icons/package.json
packages/natds-lint/package.json
packages/natds-storybook-themes/package.json
packages/natds-themes/package.json

DSY-3951
bump version cli lint storybook theme icons

bump version cli lint storybook theme icons

---

packages/natds-themes/CHANGELOG.md
packages/natds-themes/package.json
packages/natds-themes/properties/brands/aesop/dark.json
packages/natds-themes/properties/brands/avon/dark.json
packages/natds-themes/properties/brands/avon/light.json
packages/natds-themes/properties/brands/avon_v2/dark.json
packages/natds-themes/properties/brands/avon_v2/light.json
packages/natds-themes/properties/brands/biome/dark.json
packages/natds-themes/properties/brands/biome/light.json
packages/natds-themes/properties/brands/casaEestilo/dark.json
packages/natds-themes/properties/brands/casaEestilo/light.json
packages/natds-themes/properties/brands/consultoriaDeBeleza/dark.json
packages/natds-themes/properties/brands/consultoriaDeBeleza/light.json
packages/natds-themes/properties/brands/natura/dark.json
packages/natds-themes/properties/brands/natura/light.json
packages/natds-themes/properties/brands/natura_v2/dark.json
packages/natds-themes/properties/brands/natura_v2/light.json
packages/natds-themes/properties/brands/theBodyShop/dark.json
packages/natds-themes/properties/brands/theBodyShop/light.json

Dsy 3918 - add new colors global

Dsy 3918 - add new colors global

---

packages/natds-cli/package.json
packages/natds-icons/package.json
packages/natds-lint/package.json
packages/natds-storybook-themes/package.json
packages/natds-themes/package.json

DSY-3918
bump-version cli icons lint storybook themes

bump-version cli icons lint storybook themes

---

packages/natds-token-search/src/Form.js
packages/natds-token-search/src/Table.js
packages/natds-token-search/src/store/tokens.js

DSY-3918
feat(natds-search-tokens): omit Aesop

feat(natds-search-tokens): omit Aesop

---

packages/natds-icons/package.json

affects: @naturacosmeticos/natds-react
DSY-4086
chore(natds-react): bump version icons 1.18.2

chore(natds-react): bump version icons

---

packages/natds-themes/properties/brands/aesop/dark.json
packages/natds-themes/properties/brands/avon/dark.json
packages/natds-themes/properties/brands/avon_v2/dark.json
packages/natds-themes/properties/brands/biome/dark.json
packages/natds-themes/properties/brands/casaEestilo/dark.json
packages/natds-themes/properties/brands/consultoriaDeBeleza/dark.json
packages/natds-themes/properties/brands/natura/dark.json
packages/natds-themes/properties/brands/natura_v2/dark.json
packages/natds-themes/properties/brands/theBodyShop/dark.json

DSY-4133
fix neutrals dark mode

fix(natds-themes): fix neutrals dark mode

---

packages/natds-themes/properties/globals/color/dark.json
packages/natds-themes/properties/globals/color/light.json
packages/natds-token-search/src/Table.js

DSY-4236
added color primitives light dark

feat(natds-themes): added color primitives light dark

---

scripts/update_icons.sh

affects: infra
DSY-4228
added script_icons.sh

chore(infra): added script_icons.sh

---

packages/natds-themes/properties/brands/aesop/dark.json
packages/natds-themes/properties/brands/aesop/light.json
packages/natds-themes/properties/brands/avon/dark.json
packages/natds-themes/properties/brands/avon/light.json
packages/natds-themes/properties/brands/avon_v2/dark.json
packages/natds-themes/properties/brands/avon_v2/light.json
packages/natds-themes/properties/brands/biome/dark.json
packages/natds-themes/properties/brands/biome/light.json
packages/natds-themes/properties/brands/casaEestilo/dark.json
packages/natds-themes/properties/brands/casaEestilo/light.json
packages/natds-themes/properties/brands/consultoriaDeBeleza/dark.json
packages/natds-themes/properties/brands/consultoriaDeBeleza/light.json
packages/natds-themes/properties/brands/natura/dark.json
packages/natds-themes/properties/brands/natura/light.json
packages/natds-themes/properties/brands/natura_v2/dark.json
packages/natds-themes/properties/brands/natura_v2/light.json
packages/natds-themes/properties/brands/theBodyShop/dark.json
packages/natds-themes/properties/brands/theBodyShop/light.json
packages/natds-themes/properties/globals/color/dark.json
packages/natds-themes/properties/globals/color/light.json
packages/natds-token-search/src/RadioGroup.js
packages/natds-token-search/src/Table.js

Added semantic colors content surface background

Dsy 4262 semantic colors

---

packages/natds-themes/config/react-native/static/index.js
packages/natds-themes/config/shared/constants.js
packages/natds-themes/config/web/static/index.js
packages/natds-themes/properties/brands/natura_v3/asset-dark.json
packages/natds-themes/properties/brands/natura_v3/asset-light.json
packages/natds-themes/properties/brands/natura_v3/components/button.json
packages/natds-themes/properties/brands/natura_v3/components/shortcut.json
packages/natds-themes/properties/brands/natura_v3/dark.json
packages/natds-themes/properties/brands/natura_v3/light.json
packages/natds-themes/properties/brands/natura_v3/spectrum.js
packages/natds-themes/properties/brands/natura_v3/spectrum.json
packages/natds-themes/properties/brands/natura_v3/spectrum.test.js
packages/natds-themes/properties/brands/natura_v3/typography.json
packages/natds-themes/properties/globals/borderRadius/borderRadius.json
packages/natds-token-search/src/Form.js
packages/natds-token-search/src/Radio.js
packages/natds-token-search/src/store/tokens.js

Dsy 4268 added new theme natura_v3

---

packages/natds-themes/properties/brands/aesop/dark.json
packages/natds-themes/properties/brands/aesop/light.json
packages/natds-themes/properties/brands/avon/dark.json
packages/natds-themes/properties/brands/avon/light.json
packages/natds-themes/properties/brands/avon_v2/dark.json
packages/natds-themes/properties/brands/avon_v2/light.json
packages/natds-themes/properties/brands/biome/dark.json
packages/natds-themes/properties/brands/biome/light.json
packages/natds-themes/properties/brands/casaEestilo/dark.json
packages/natds-themes/properties/brands/casaEestilo/light.json
packages/natds-themes/properties/brands/consultoriaDeBeleza/dark.json
packages/natds-themes/properties/brands/consultoriaDeBeleza/light.json
packages/natds-themes/properties/brands/natura/dark.json
packages/natds-themes/properties/brands/natura/light.json
packages/natds-themes/properties/brands/natura_v2/dark.json
packages/natds-themes/properties/brands/natura_v2/light.json
packages/natds-themes/properties/brands/natura_v3/dark.json
packages/natds-themes/properties/brands/natura_v3/light.json
packages/natds-themes/properties/brands/theBodyShop/dark.json
packages/natds-themes/properties/brands/theBodyShop/light.json
packages/natds-token-search/src/Table.js

Dsy 4311 added colorInfo in feedback group

Dsy 4311 added colorInfo

---

packages/natds-icons/CHANGELOG.md

Update icons CHANGELOG.md

---

scripts/build-regression-comment.sh

affects: infra
DSY-0000
fix script build-regression-comment

chore(infra): fix script build-regression-comment

---

packages/natds-themes/properties/brands/aesop/components/button.json
packages/natds-themes/properties/brands/avon/components/button.json
packages/natds-themes/properties/brands/avon_v2/components/button.json
packages/natds-themes/properties/brands/biome/components/button.json
packages/natds-themes/properties/brands/biome/dark.json
packages/natds-themes/properties/brands/biome/light.json
packages/natds-themes/properties/brands/casaEestilo/components/button.json
packages/natds-themes/properties/brands/consultoriaDeBeleza/components/button.json
packages/natds-themes/properties/brands/natdsTest/components/button.json
packages/natds-themes/properties/brands/natdsTest/dark.json
packages/natds-themes/properties/brands/natdsTest/light.json
packages/natds-themes/properties/brands/natura/components/button.json
packages/natds-themes/properties/brands/natura/dark.json
packages/natds-themes/properties/brands/natura_v2/components/button.json
packages/natds-themes/properties/brands/natura_v3/components/button.json
packages/natds-themes/properties/brands/theBodyShop/components/button.json
packages/natds-themes/properties/globals/color/dark.json
packages/natds-themes/properties/globals/color/light.json
packages/natds-themes/properties/globals/components/button.json

Added new colors and sates to buton component
Added buttonElevation

Dsy 4671 Added new colors and states in button component

---

packages/natds-themes/properties/brands/aesop/components/button.json
packages/natds-themes/properties/brands/avon/components/button.json
packages/natds-themes/properties/brands/avon_v2/components/button.json
packages/natds-themes/properties/brands/biome/components/button.json
packages/natds-themes/properties/brands/casaEestilo/components/button.json
packages/natds-themes/properties/brands/consultoriaDeBeleza/components/button.json
packages/natds-themes/properties/brands/natdsTest/components/button.json
packages/natds-themes/properties/brands/natura/components/button.json
packages/natds-themes/properties/brands/natura_v2/components/button.json
packages/natds-themes/properties/brands/natura_v3/components/button.json
packages/natds-themes/properties/brands/theBodyShop/components/button.json
packages/natds-themes/properties/globals/components/button.json

DSY-4720
added button paddindX textTransform

feat(natds-themes): added button paddindX textTransform

---

packages/natds-themes/properties/brands/natura_v2/light.json

DSY-4810
fixed color onPrimaryLightest Natura V2

fix(natds-themes): fixed color onPrimaryLightest Natura V2

---

packages/natds-themes/config/react-native/static/index.js
packages/natds-themes/config/shared/constants.js
packages/natds-themes/config/web/static/index.js
packages/natds-themes/properties/brands/casaEestilo/components/button.json
packages/natds-themes/properties/brands/casaEestilo_v2/asset-dark.json
packages/natds-themes/properties/brands/casaEestilo_v2/asset-light.json
packages/natds-themes/properties/brands/casaEestilo_v2/components/button.json
packages/natds-themes/properties/brands/casaEestilo_v2/components/shortcut.json
packages/natds-themes/properties/brands/casaEestilo_v2/dark.json
packages/natds-themes/properties/brands/casaEestilo_v2/light.json
packages/natds-themes/properties/brands/casaEestilo_v2/spectrum.js
packages/natds-themes/properties/brands/casaEestilo_v2/spectrum.json
packages/natds-themes/properties/brands/casaEestilo_v2/spectrum.test.js
packages/natds-themes/properties/brands/casaEestilo_v2/typography.json
packages/natds-themes/properties/brands/consultoriaDeBeleza/components/button.json
packages/natds-themes/properties/brands/forcaDeVendas/asset-dark.json
packages/natds-themes/properties/brands/forcaDeVendas/asset-light.json
packages/natds-themes/properties/brands/forcaDeVendas/components/button.json
packages/natds-themes/properties/brands/forcaDeVendas/components/shortcut.json
packages/natds-themes/properties/brands/forcaDeVendas/dark.json
packages/natds-themes/properties/brands/forcaDeVendas/light.json
packages/natds-themes/properties/brands/forcaDeVendas/spectrum.js
packages/natds-themes/properties/brands/forcaDeVendas/spectrum.json
packages/natds-themes/properties/brands/forcaDeVendas/spectrum.test.js
packages/natds-themes/properties/brands/forcaDeVendas/typography.json
packages/natds-token-search/src/Form.js
packages/natds-token-search/src/Radio.js
packages/natds-token-search/src/store/tokens.js

Dsy 4393 adding 2 new themes forcaDeVendas casaEestilo_v2

---

packages/natds-themes/properties/brands/casaEestilo_v2/asset-dark.json
packages/natds-themes/properties/brands/casaEestilo_v2/asset-light.json

DSY-4983
change path logo casa & estilo v2

fix(natds-themes): change path logo casa & estilo v2

---

packages/natds-themes/README.md
packages/natds-themes/properties/brands/aesop/dark.json
packages/natds-themes/properties/brands/aesop/light.json
packages/natds-themes/properties/brands/avon/dark.json
packages/natds-themes/properties/brands/avon/light.json
packages/natds-themes/properties/brands/avon_v2/dark.json
packages/natds-themes/properties/brands/avon_v2/light.json
packages/natds-themes/properties/brands/biome/dark.json
packages/natds-themes/properties/brands/biome/light.json
packages/natds-themes/properties/brands/casaEestilo/dark.json
packages/natds-themes/properties/brands/casaEestilo/light.json
packages/natds-themes/properties/brands/casaEestilo_v2/dark.json
packages/natds-themes/properties/brands/casaEestilo_v2/light.json
packages/natds-themes/properties/brands/consultoriaDeBeleza/dark.json
packages/natds-themes/properties/brands/consultoriaDeBeleza/light.json
packages/natds-themes/properties/brands/forcaDeVendas/dark.json
packages/natds-themes/properties/brands/forcaDeVendas/light.json
packages/natds-themes/properties/brands/natura/dark.json
packages/natds-themes/properties/brands/natura/light.json
packages/natds-themes/properties/brands/natura_v2/dark.json
packages/natds-themes/properties/brands/natura_v2/light.json
packages/natds-themes/properties/brands/natura_v3/dark.json
packages/natds-themes/properties/brands/natura_v3/light.json
packages/natds-themes/properties/brands/theBodyShop/dark.json
packages/natds-themes/properties/brands/theBodyShop/light.json
packages/natds-themes/properties/globals/color/dark.json
packages/natds-themes/properties/globals/color/light.json

Dsy 5039 - update colors feadback primitive references

Dsy 5039 - update colors feadback primitive references

---

packages/natds-themes/properties/brands/aesop/dark.json
packages/natds-themes/properties/brands/aesop/light.json
packages/natds-themes/properties/brands/avon/dark.json
packages/natds-themes/properties/brands/avon/light.json
packages/natds-themes/properties/brands/avon_v2/dark.json
packages/natds-themes/properties/brands/avon_v2/light.json
packages/natds-themes/properties/brands/biome/dark.json
packages/natds-themes/properties/brands/biome/light.json
packages/natds-themes/properties/brands/casaEestilo/dark.json
packages/natds-themes/properties/brands/casaEestilo/light.json
packages/natds-themes/properties/brands/casaEestilo_v2/dark.json
packages/natds-themes/properties/brands/casaEestilo_v2/light.json
packages/natds-themes/properties/brands/consultoriaDeBeleza/dark.json
packages/natds-themes/properties/brands/consultoriaDeBeleza/light.json
packages/natds-themes/properties/brands/forcaDeVendas/dark.json
packages/natds-themes/properties/brands/forcaDeVendas/light.json
packages/natds-themes/properties/brands/natura/dark.json
packages/natds-themes/properties/brands/natura/light.json
packages/natds-themes/properties/brands/natura_v2/dark.json
packages/natds-themes/properties/brands/natura_v2/light.json
packages/natds-themes/properties/brands/natura_v3/dark.json
packages/natds-themes/properties/brands/natura_v3/light.json
packages/natds-themes/properties/brands/theBodyShop/dark.json
packages/natds-themes/properties/brands/theBodyShop/light.json
packages/natds-themes/properties/globals/color/dark.json
packages/natds-themes/properties/globals/color/light.json

DSY-5055
fix(natds-themes): fixed primitive reference

fix(natds-themes): fixed primitive reference

---

packages/natds-themes/properties/brands/aesop/dark.json
packages/natds-themes/properties/brands/aesop/light.json
packages/natds-themes/properties/brands/avon/dark.json
packages/natds-themes/properties/brands/avon/light.json
packages/natds-themes/properties/brands/avon_v2/dark.json
packages/natds-themes/properties/brands/avon_v2/light.json
packages/natds-themes/properties/brands/biome/dark.json
packages/natds-themes/properties/brands/biome/light.json
packages/natds-themes/properties/brands/casaEestilo/dark.json
packages/natds-themes/properties/brands/casaEestilo/light.json
packages/natds-themes/properties/brands/casaEestilo_v2/dark.json
packages/natds-themes/properties/brands/casaEestilo_v2/light.json
packages/natds-themes/properties/brands/consultoriaDeBeleza/dark.json
packages/natds-themes/properties/brands/consultoriaDeBeleza/light.json
packages/natds-themes/properties/brands/forcaDeVendas/dark.json
packages/natds-themes/properties/brands/forcaDeVendas/light.json
packages/natds-themes/properties/brands/natdsTest/dark.json
packages/natds-themes/properties/brands/natdsTest/light.json
packages/natds-themes/properties/brands/natura/dark.json
packages/natds-themes/properties/brands/natura/light.json
packages/natds-themes/properties/brands/natura_v2/dark.json
packages/natds-themes/properties/brands/natura_v2/light.json
packages/natds-themes/properties/brands/natura_v3/dark.json
packages/natds-themes/properties/brands/natura_v3/light.json
packages/natds-themes/properties/brands/theBodyShop/dark.json
packages/natds-themes/properties/brands/theBodyShop/light.json
packages/natds-themes/properties/globals/color/dark.json
packages/natds-themes/properties/globals/color/light.json

DSY-5153
Added color neutral75

feat(natds-themes): added color neutral75

---

packages/natds-themes/properties/brands/forcaDeVendas/components/button.json

DSY-5153
change theme FV textTransform to none

fix(natds-themes): change theme FV textTransform to none

---

packages/natds-themes/properties/brands/consultoriaDeBeleza/components/button.json
packages/natds-themes/properties/brands/forcaDeVendas/components/select.json
packages/natds-themes/properties/brands/natura_v3/components/button.json
packages/natds-themes/properties/brands/theBodyShop/components/counter.json

Dsy 5392 fix tokens components

Dsy 5392 fix tokens components

---

packages/natds-themes/config/react-native/static/index.js
packages/natds-themes/config/shared/constants.js
packages/natds-themes/config/web/static/index.js
packages/natds-themes/properties/brands/forcaDeVendas/components/counter.json
packages/natds-themes/properties/brands/forcaDeVendas/components/select.json
packages/natds-themes/properties/brands/forcaDeVendas_v2/asset-dark.json
packages/natds-themes/properties/brands/forcaDeVendas_v2/asset-light.json
packages/natds-themes/properties/brands/forcaDeVendas_v2/components/button.json
packages/natds-themes/properties/brands/forcaDeVendas_v2/components/counter.json
packages/natds-themes/properties/brands/forcaDeVendas_v2/components/select.json
packages/natds-themes/properties/brands/forcaDeVendas_v2/components/shortcut.json
packages/natds-themes/properties/brands/forcaDeVendas_v2/components/textfield.json
packages/natds-themes/properties/brands/forcaDeVendas_v2/dark.json
packages/natds-themes/properties/brands/forcaDeVendas_v2/light.json
packages/natds-themes/properties/brands/forcaDeVendas_v2/spectrum.js
packages/natds-themes/properties/brands/forcaDeVendas_v2/spectrum.json
packages/natds-themes/properties/brands/forcaDeVendas_v2/spectrum.test.js
packages/natds-themes/properties/brands/forcaDeVendas_v2/typography.json
packages/natds-token-search/src/Form.js
packages/natds-token-search/src/Radio.js
packages/natds-token-search/src/store/tokens.js

Dsy 5412 added theme Forca de vendas V2

Dsy 5412 added theme Forca de vendas V2

---

packages/natds-themes/properties/brands/consultoriaDeBeleza_v2/components/button.json
packages/natds-themes/properties/brands/forcaDeVendas_v2/components/button.json

DSY-5430
fixed textTransform CB2 FV2 to none

fix(natds-themes):  fixed textTransform CB2 FV2 to none

---

packages/natds-themes/properties/brands/consultoriaDeBeleza_v2/asset-dark.json
packages/natds-themes/properties/brands/consultoriaDeBeleza_v2/asset-light.json

DSY-5461
fix(natds-themes):  fixed CB-V2 assets logo AB PT-BR ES  height / width

fix(natds-themes):  fixed CB-V2 assets logo AB PT-BR ES  height / width

---

packages/natds-themes/properties/brands/consultoriaDeBeleza_v2/asset-dark.json
packages/natds-themes/properties/brands/consultoriaDeBeleza_v2/asset-light.json
packages/natds-themes/properties/brands/forcaDeVendas_v2/asset-dark.json
packages/natds-themes/properties/brands/forcaDeVendas_v2/asset-light.json

DSY-5461
fix(natds-themes):  fixed CB-V2 e FV2  default language PT

fix(natds-themes):  fixed CB-V2 e FV2  default language PT

---

packages/natds-themes/properties/brands/avon_v3/asset-dark.json
packages/natds-themes/properties/brands/avon_v3/asset-light.json
packages/natds-themes/properties/brands/avon_v3/components/counter.json
packages/natds-themes/properties/brands/avon_v3/components/select.json
packages/natds-themes/properties/brands/avon_v3/components/textfield.json
packages/natds-themes/properties/brands/avon_v3/dark.json

DSY-5577
fix(natds-themes): fix borderRadius counter select textField Avon-v3

fix(natds-themes): fix borderRadius counter select textField Avon-v3

---

packages/natds-themes/properties/brands/aesop/light.json
packages/natds-themes/properties/brands/avon/light.json
packages/natds-themes/properties/brands/avon_v2/light.json
packages/natds-themes/properties/brands/avon_v3/components/button.json
packages/natds-themes/properties/brands/avon_v3/dark.json
packages/natds-themes/properties/brands/avon_v3/light.json
packages/natds-themes/properties/brands/biome/light.json
packages/natds-themes/properties/brands/casaEestilo/light.json
packages/natds-themes/properties/brands/casaEestilo_v2/light.json
packages/natds-themes/properties/brands/consultoriaDeBeleza/light.json
packages/natds-themes/properties/brands/consultoriaDeBeleza_v2/light.json
packages/natds-themes/properties/brands/forcaDeVendas/light.json
packages/natds-themes/properties/brands/forcaDeVendas_v2/light.json
packages/natds-themes/properties/brands/natdsTest/light.json
packages/natds-themes/properties/brands/natura/light.json
packages/natds-themes/properties/brands/natura_v2/light.json
packages/natds-themes/properties/brands/natura_v3/light.json
packages/natds-themes/properties/brands/theBodyShop/light.json

DSY-5577
fixed onSuccess = neutral0 and textTransform avon-v3 = uppercase

fix(natds-themes):  fixed onSuccess and textTransform

---

packages/natds-themes/properties/brands/aesop/light.json
packages/natds-themes/properties/brands/avon/light.json
packages/natds-themes/properties/brands/avon_v2/light.json
packages/natds-themes/properties/brands/avon_v3/light.json
packages/natds-themes/properties/brands/biome/light.json
packages/natds-themes/properties/brands/casaEestilo/light.json
packages/natds-themes/properties/brands/casaEestilo_v2/light.json
packages/natds-themes/properties/brands/consultoriaDeBeleza/light.json
packages/natds-themes/properties/brands/consultoriaDeBeleza_v2/light.json
packages/natds-themes/properties/brands/forcaDeVendas/light.json
packages/natds-themes/properties/brands/forcaDeVendas_v2/light.json
packages/natds-themes/properties/brands/natdsTest/light.json
packages/natds-themes/properties/brands/natura/light.json
packages/natds-themes/properties/brands/natura_v2/light.json
packages/natds-themes/properties/brands/natura_v3/light.json
packages/natds-themes/properties/brands/theBodyShop/light.json
packages/natds-themes/properties/globals/color/light.json

fix(natds-themes):  fixed onAlert color

---

packages/natds-themes/properties/brands/avon_v3/components/button.json

DSY-5577
fix(natds-themes): fix textTransform = none

fix(natds-themes): fix textTransform = none

---

packages/natds-themes/properties/brands/avon_v3/asset-dark.json
packages/natds-themes/properties/brands/avon_v3/asset-light.json

affects: @naturacosmeticos/natds-rn
DSY-5578
fix(natds-rn): logo Avon -V3 height in position A and custom A

fix(natds-rn): logo Avon -V3 height in position A and custom A

---

packages/natds-themes/properties/brands/avon_v3/light.json

DSY-5578
fixed color secondaryDark and secondaryDarkest

fix(natds-themes):  fixed color secondaryDark and secondaryDarkest

---

packages/natds-themes/properties/brands/natura/asset-light.json
packages/natds-themes/properties/brands/natura_v2/asset-light.json
packages/natds-themes/properties/brands/natura_v3/asset-light.json

fixt(natds-themes): fixed logo natura b custom 168 to 162

---

packages/natds-themes/properties/brands/consultoriaDeBeleza/asset-dark.json
packages/natds-themes/properties/brands/consultoriaDeBeleza/asset-light.json

fix(natds-themes): fixed logo CB1
